name: Release

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write

    steps:
      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          fetch-tags: true
          token: ${{ steps.app-token.outputs.token }}

      - run: git reset --hard ${{ github.sha }}

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          run-install: false

      - uses: astral-sh/setup-uv@v6

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          uvx --from="python-semantic-release==10.5.3" semantic-release version || true
          uvx --from="python-semantic-release==10.5.3" semantic-release publish
