name: run-boltz-tests.yml
run-name: ${{ github.actor }} is running tests for Boltz 🚀
on: [push]
jobs:
  Run-Boltz-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: install pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.62.2
          environments: >-
            boltz-dev

          cache: true
          #auth-host: prefix.dev
          #auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - name: Run Boltz tests
        run: pixi run -e boltz-dev all-tests
      - run: echo "🍏 This job's status is ${{ job.status }}."
